# Generated by Django 3.0.5 on 2024-06-27 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuestionario', models.CharField(max_length=50)),
                ('descripcion_cuestionario', models.TextField(max_length=350)),
                ('numero_preguntas', models.PositiveIntegerField()),
                ('puntaje_maximo', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('cues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionario.Cuestionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.PositiveIntegerField()),
                ('pregunta', models.CharField(max_length=600)),
                ('opcion1', models.CharField(max_length=200)),
                ('opcion2', models.CharField(max_length=200)),
                ('opcion3', models.CharField(max_length=200)),
                ('opcion4', models.CharField(max_length=200)),
                ('respuesta', models.CharField(choices=[('Opcion1', 'Opcion1'), ('Opcion2', 'Opcion2'), ('Opcion3', 'Opcion3'), ('Opcion4', 'Opcion4')], max_length=200)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionario.Cuestionario')),
            ],
        ),
    ]
